
name: MY-NODE-APP PIPELINE

on:
  push:
    branches: [main]

jobs:
  Setup-and-deploy:
    runs-on: test-web
    steps:
      - uses: actions/checkout@v4
      
         - name: Installing Dependencies
           run: npm install

         - name: Run the app
           run: pm2 start npm --name "my-node-app" -- start -- -p 3000





